version: 2

sources:
  - name: dev
    database: test_db
    tables:
      - name: bronze_weatherstack_raw
        columns:
          - name: id
          - name: city
          - name: temperature
          - name: weather_description
          - name: wind_speed
          - name: time
          - name: inserted_at
          - name: utc_offset